parameters:
  # BOOTSTRAP
  # Which glance image to use (for all instances)
  image_id: dd8c8969-5e4f-4482-9097-c5a896bc46f8
  # Which instance type to use for the mons:
  mon_flavor: m2.tiny
  # Which instance type to use for the storage (OSD) nodes:
  storage_node_flavor: m2.tiny
  # Where to launch all the instances in this cluster:
  az: NCI
  #The Keystone SSH key-pair.  Use ssh -A to hop from login to cluster nodes
  ssh_key_name: hoolio

  # CEPH
  # Extra packages to install on the login node:
  login_node_extra_packages: ansible git curl python-pip
  # Extra packages to install on the nodes:
  node_extra_packages: git
  # The total number of metadata servers (for cephfs)
  metadata_node_count: 2
  # The total number of Monitor Nodes:
  mon_count: 3
  # How many storage (OSD) nodes to create:
  storage_node_count: 7
  # For each storage node, how many volumes (OSDs):
  osds_per_storage_node: 4
  #The size of each OSD volume:
  osd_volume_size_in_gb: 1
