heat_template_version: 2013-05-23

parameters:
  image_id:
    type: string
  mon_flavor:
    type: string
  storage_node_flavor:
    type: string
  az:
    type: string
  ssh_key_name:
    type: string

  login_node_extra_packages:
    type: string
  node_extra_packages:
    type: string
  mon_count:
    type: number
  storage_node_count:
    type: number
  osds_per_storage_node:
    type: number
  osd_volume_size_in_gb:
    type: number
  metadata_node_count:
    type: number
  ceph_release_name:
    type: string
  # osd_journal_volume_size_in_gb:
  #   type: number

resources:
  cluster_internal:
    type: OS::Neutron::SecurityGroup
    properties:
      name: cluster_internal
      description: all ports open but only to other cluster nodes
      rules:
        - protocol: icmp
          remote_mode: remote_group_id
        - protocol: tcp
          remote_mode: remote_group_id

  external_inbound:
    type: OS::Neutron::SecurityGroup
    properties:
      name: external_inbound
      description: ssh and ping from anywhere
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22

  random_string:
    type: OS::Heat::RandomString
    properties:
      length: 3
      sequence: lowercase

  storage-nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: storage_node_count }
      resource_def:
        type: heat_storage_node_template.yaml
        properties:
          node_extra_packages: { get_param: node_extra_packages }
          image_id: { get_param: image_id }
          storage_node_flavor: { get_param: storage_node_flavor }
          osds_per_storage_node: { get_param: osds_per_storage_node }
          ssh_key_name: { get_param: ssh_key_name }
          osd_volume_size_in_gb: { get_param: osd_volume_size_in_gb }
          ceph_release_name: { get_param: ceph_release_name }
          az: { get_param: az }
          storage_node_name:
            str_replace:
              template: storage-%index%-$random_string
              params:
                $random_string: { get_resource: random_string }

  mons:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: mon_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          metadata:
            ansible_host_groups: mons
            ansible_host_vars: role=master
          key_name: { get_param: ssh_key_name }
          image: { get_param: image_id }
          flavor: { get_param: mon_flavor }
          availability_zone: { get_param: az }
          security_groups:
            - {get_resource: external_inbound}
            - {get_resource: cluster_internal}
          name:
            str_replace:
              template: mon-%index%-$random_string
              params:
                $random_string: { get_resource: random_string }
          user_data:
            str_replace:
              template: |
                #!/bin/bash -v
                wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
                echo deb http://download.ceph.com/debian-$CEPH_RELEASE/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
                sudo apt-get update
                DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -q $EXTRA_PACKAGES
              params:
                $EXTRA_PACKAGES: { get_param: node_extra_packages }
                $CEPH_RELEASE: { get_param: ceph_release_name }

  metadata-nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: metadata_node_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          metadata:
            ansible_host_groups: mds
            ansible_host_vars: role=master
          key_name: { get_param: ssh_key_name }
          image: { get_param: image_id }
          flavor: { get_param: mon_flavor }
          availability_zone: { get_param: az }
          security_groups:
            - {get_resource: external_inbound}
            - {get_resource: cluster_internal}
          name:
            str_replace:
              template: mds-%index%-$random_string
              params:
                $random_string: { get_resource: random_string }
          user_data:
            str_replace:
              template: |
                #!/bin/bash -v
                wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
                echo deb http://download.ceph.com/debian-$CEPH_RELEASE/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
                sudo apt-get update
                DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -q $EXTRA_PACKAGES
              params:
                $EXTRA_PACKAGES: { get_param: node_extra_packages }
                $CEPH_RELEASE: { get_param: ceph_release_name }

  login-node:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: OS::Nova::Server
        properties:
          metadata:
            ansible_host_groups: login
            ansible_host_vars: role=master
          key_name: { get_param: ssh_key_name }
          image: { get_param: image_id }
          flavor: { get_param: storage_node_flavor }
          availability_zone: { get_param: az }
          security_groups:
            - {get_resource: external_inbound}
            - {get_resource: cluster_internal}
          name:
            str_replace:
              template: login-node-$random_string
              params:
                $random_string: { get_resource: random_string }
          user_data:
            str_replace:
              template: |
                #!/bin/bash -v
                wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
                echo deb http://download.ceph.com/debian-$CEPH_RELEASE/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
                sudo apt-get update
                sudo apt-get install -y $EXTRA_PACKAGES
              params:
                $EXTRA_PACKAGES: { get_param: login_node_extra_packages }

outputs:
  login-node-public-ip:
    description: Cluster admin node; to auth to other nodes, use `ssh -A`.
    value: { get_attr: [login-node, first_address]}
